### ISSUE TITLE
create Vagrant file for new image

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger-labs/umbra#11]
Create a Vagrantfile that contains the latest umbra code 
dependencies: Ubuntu 20.04, (Python 3.8), Docker
make download or make vm -> either builds or downloads vm

https://github.com/raphaelvrosa/umbra/blob/master/Makefile

PR:
vagrant file on root

**Comment by raphaelvrosa** [comment]
Vagrantfile added and instructions added to makefile.
